
import { AspectRatioOption, TabOption, OptionItem } from './types';
import { Monitor, Camera, Smile, LayoutTemplate, Box } from 'lucide-react';

export const TABS: TabOption[] = [
  { id: 'views', label: 'Views', subLabel: '(시점)', icon: Box },
  { id: 'angles', label: 'Angles', subLabel: '(앵글 & 렌즈)', icon: Camera },
  { id: 'expressions', label: 'Expressions', subLabel: '(표정)', icon: Smile },
  { id: 'ratios', label: 'Aspect Ratios', subLabel: '(종횡비)', icon: LayoutTemplate },
];

export const ASPECT_RATIOS: AspectRatioOption[] = [
  { id: '1:1', label: '1:1', subLabel: '(Square / 스퀘어)', value: '1:1', iconType: 'square' },
  { id: '3:4', label: '3:4', subLabel: '(Portrait / 세로형)', value: '3:4', iconType: 'portrait' },
  { id: '4:3', label: '4:3', subLabel: '(Landscape / 가로형)', value: '4:3', iconType: 'landscape' },
  { id: '2:3', label: '2:3', subLabel: '(Classic Portrait / 클래식 세로)', value: '2:3', iconType: 'classicPortrait' },
  { id: '3:2', label: '3:2', subLabel: '(Classic Landscape / 클래식 가로)', value: '3:2', iconType: 'classicLandscape' },
  { id: '16:9', label: '16:9', subLabel: '(Wide / 와이드)', value: '16:9', iconType: 'wide' },
  { id: '9:16', label: '9:16', subLabel: '(Stories / 스토리)', value: '9:16', iconType: 'tall' },
  { id: '21:9', label: '21:9', subLabel: '(Ultrawide / 시네마틱)', value: '21:9', iconType: 'cinema' },
  { id: '1:2', label: '1:2', subLabel: '(Tall / 톨)', value: '1:2', iconType: 'tall' },
  { id: '2:1', label: '2:1', subLabel: '(Panorama / 파노라마)', value: '2:1', iconType: 'panorama' },
];

export const VIEWS: OptionItem[] = [
  { id: 'front', label: 'Front View', subLabel: '(정면)', value: 'Front View' },
  { id: '3/4-front', label: '3/4 Front View', subLabel: '(3/4 앞모습)', value: '3/4 Front View' },
  { id: 'side', label: 'Side View', subLabel: '(측면 / 옆모습)', value: 'Side View' },
  { id: 'extreme-side', label: 'Extreme Side View', subLabel: '(정확한 옆 라인)', value: 'Extreme Side View' },
  { id: 'back', label: 'Back View', subLabel: '(후면)', value: 'Back View' },
  { id: '3/4-back', label: '3/4 Back View', subLabel: '(3/4 뒷모습)', value: '3/4 Back View' },
  { id: 'top', label: 'Top View', subLabel: '(탑뷰 / 위에서 본 시점)', value: 'Top View' },
  { id: 'bottom', label: 'Bottom View', subLabel: '(밑뷰 / 바닥에서 올려본 시점)', value: 'Bottom View' },
  { id: 'quarter-turn', label: 'Quarter Turn View', subLabel: '(사선 회전 뷰)', value: 'Quarter Turn View' },
  { id: 'overhead-down', label: 'Overhead Down Angle', subLabel: '(사선 위에서 내려다보기)', value: 'Overhead Down Angle' },
  { id: 'underneath-up', label: 'Underneath Up Angle', subLabel: '(사선 아래에서 올려다보기)', value: 'Underneath Up Angle' },
  { id: 'isometric', label: 'Isometric View', subLabel: '(아이소메트릭 뷰)', value: 'Isometric View' },
  { id: 'dynamic', label: 'Dynamic Angle View', subLabel: '(다이내믹 앵글)', value: 'Dynamic Angle View' },
  { id: 'face', label: 'Face View', subLabel: '(얼굴 뷰)', value: 'Face View' },
  { id: 'over-shoulder', label: 'Over-the-Shoulder', subLabel: '(어깨 너머 시점)', value: 'Over-the-Shoulder' },
  { id: 'pov', label: 'POV View', subLabel: '(1인칭 시점)', value: 'POV View' },
  { id: 'selfie', label: 'Selfie View', subLabel: '(셀카 앵글)', value: 'Selfie View' },
];

export const ANGLES: OptionItem[] = [
  { id: 'eye-level', label: 'Eye Level Shot', subLabel: '(아이 레벨 / 눈높이)', value: 'Eye Level Shot' },
  { id: 'high-angle', label: 'High Angle Shot', subLabel: '(하이 앵글 / 부감)', value: 'High Angle Shot' },
  { id: 'extreme-high', label: 'Extreme High Angle', subLabel: '(익스트림 하이 / 수직 부감)', value: 'Extreme High Angle' },
  { id: 'aerial', label: 'Aerial View', subLabel: '(에어리얼 뷰 / 항공 샷)', value: 'Aerial View' },
  { id: 'drone', label: 'Aerial-Drone Shot', subLabel: '(드론 샷)', value: 'Aerial-Drone Shot' },
  { id: 'above', label: 'Photo from Above', subLabel: '(위에서 찍은 샷)', value: 'Photo from Above' },
  { id: 'overhead', label: 'Overhead / Top View', subLabel: '(오버헤드 / 탑뷰)', value: 'Overhead / Top View' },
  { id: 'birds-eye', label: 'Birds Eye View', subLabel: '(버즈 아이 뷰 / 조감도)', value: 'Birds Eye View' },
  { id: 'low-angle', label: 'Low Angle Shot', subLabel: '(로우 앵글 / 앙각)', value: 'Low Angle Shot' },
  { id: 'extreme-low', label: 'Extreme Low Angle', subLabel: '(익스트림 로우 앵글)', value: 'Extreme Low Angle' },
  { id: 'wide-angle', label: 'Wide Angle Shot', subLabel: '(와이드 앵글 / 광각)', value: 'Wide Angle Shot' },
  { id: 'full-body', label: 'Full Body Shot', subLabel: '(풀 바디 / 전신)', value: 'Full Body Shot' },
  { id: 'medium', label: 'Medium Shot', subLabel: '(미디엄 샷 / 상반신)', value: 'Medium Shot' },
  { id: 'close-up', label: 'Close Up Shot', subLabel: '(클로즈업)', value: 'Close Up Shot' },
  { id: 'extreme-close-up', label: 'Extreme Close Up', subLabel: '(익스트림 클로즈업 / 초근접)', value: 'Extreme Close Up' },
  { id: 'detail', label: 'Detail Shot', subLabel: '(디테일 샷 / 세부 묘사)', value: 'Detail Shot' },
  { id: 'side-angle', label: 'Side Angle Shot', subLabel: '(사이드 앵글 / 측면)', value: 'Side Angle Shot' },
  { id: 'side-profile', label: 'Side Profile Shot', subLabel: '(사이드 프로필 / 옆모습)', value: 'Side Profile Shot' },
  { id: 'two-shot', label: 'Two Shot', subLabel: '(투 샷 / 2인)', value: 'Two Shot' },
  { id: 'behind', label: 'Shot from Behind', subLabel: '(뒷모습)', value: 'Shot from Behind' },
  { id: 'ots', label: 'Over-the-Shoulder', subLabel: '(오버 더 숄더 / 어깨 걸고)', value: 'Over-the-Shoulder' },
  { id: 'pov-shot', label: 'POV Shot', subLabel: '(1인칭 시점)', value: 'POV Shot' },
  { id: 'tracking', label: 'Tracking / Dolly', subLabel: '(트래킹 / 돌리 샷)', value: 'Tracking / Dolly' },
  { id: 'tilted', label: 'Tilted Shot', subLabel: '(틸트 / 기울기)', value: 'Tilted Shot' },
  { id: 'dutch', label: 'Dutch Angle', subLabel: '(더치 앵글)', value: 'Dutch Angle' },
  { id: 'diagonal', label: 'Diagonal Shot', subLabel: '(대각선 구도)', value: 'Diagonal Shot' },
  { id: 'off-center-cu', label: 'Off-center Close Up', subLabel: '(오프 센터 클로즈업)', value: 'Off-center Close Up' },
  { id: 'off-center', label: 'Off-center Shot', subLabel: '(오프 센터 / 여백)', value: 'Off-center Shot' },
  { id: 'rule-thirds', label: 'Rule of Thirds', subLabel: '(3분할 구도)', value: 'Rule of Thirds' },
  { id: 'silhouette', label: 'Silhouette Shot', subLabel: '(실루엣 / 역광)', value: 'Silhouette Shot' },
  { id: 'candid', label: 'Candid Shot', subLabel: '(캔디드 / 스냅)', value: 'Candid Shot' },
  { id: 'foot', label: 'Foot on Pavement', subLabel: '(발 샷 / 바닥 시점)', value: 'Foot on Pavement' },
  { id: 'underwater', label: 'Underwater Shot', subLabel: '(수중 촬영)', value: 'Underwater Shot' },
];

export const EXPRESSIONS: OptionItem[] = [
  { id: 'neutral', label: 'Neutral', subLabel: '(중립 / 무표정)', value: 'Neutral expression' },
  { id: 'happy', label: 'Happy', subLabel: '(행복 / 웃음)', value: 'Happy expression' },
  { id: 'laughing', label: 'Laughing', subLabel: '(크게 웃음 / 폭소)', value: 'Laughing expression' },
  { id: 'sad', label: 'Sad', subLabel: '(슬픔)', value: 'Sad expression' },
  { id: 'crying', label: 'Crying', subLabel: '(울음 / 눈물)', value: 'Crying expression' },
  { id: 'angry', label: 'Angry', subLabel: '(분노)', value: 'Angry expression' },
  { id: 'furious', label: 'Furious', subLabel: '(격노 / 크게 화남)', value: 'Furious expression' },
  { id: 'surprised', label: 'Surprised', subLabel: '(놀람 / 깜짝)', value: 'Surprised expression' },
  { id: 'shocked', label: 'Shocked', subLabel: '(충격 / 경악)', value: 'Shocked expression' },
  { id: 'scared', label: 'Scared', subLabel: '(공포 / 두려움)', value: 'Scared expression' },
  { id: 'worried', label: 'Worried', subLabel: '(걱정 / 불안)', value: 'Worried expression' },
  { id: 'confused', label: 'Confused', subLabel: '(혼란 / 갸우뚱)', value: 'Confused expression' },
  { id: 'curious', label: 'Curious', subLabel: '(호기심 / 궁금)', value: 'Curious expression' },
  { id: 'embarrassed', label: 'Embarrassed', subLabel: '(당황 / 민망)', value: 'Embarrassed expression' },
  { id: 'shy', label: 'Shy', subLabel: '(수줍음)', value: 'Shy expression' },
  { id: 'disgusted', label: 'Disgusted', subLabel: '(혐오 / 역겨움)', value: 'Disgusted expression' },
  { id: 'smug', label: 'Smug', subLabel: '(얄밉게 자신감 있는 표정)', value: 'Smug expression' },
  { id: 'tired', label: 'Tired', subLabel: '(피곤 / 지침)', value: 'Tired expression' },
  { id: 'sleepy', label: 'Sleepy', subLabel: '(졸림)', value: 'Sleepy expression' },
  { id: 'excited', label: 'Excited', subLabel: '(신남 / 들뜸)', value: 'Excited expression' },
  { id: 'proud', label: 'Proud', subLabel: '(자랑스러움 / 뿌듯함)', value: 'Proud expression' },
  { id: 'determined', label: 'Determined', subLabel: '(결의 / 단호)', value: 'Determined expression' },
  { id: 'thinking', label: 'Thinking', subLabel: '(생각 중 / 고개 갸웃)', value: 'Thinking expression' },
  { id: 'mischievous', label: 'Mischievous', subLabel: '(장난스러움)', value: 'Mischievous expression' },
  { id: 'blushing', label: 'Blushing', subLabel: '(얼굴 붉힘 / 부끄러움)', value: 'Blushing expression' },
];
